### PR TITLE
Update idb2pat for IDA 7.4+

### PR DESCRIPTION
**Pull request by KulaGGin**
Update idb2pat for IDA 7.4+ to fix problems with member names shown in issue #104

### CODE REVIEW

**Comment by williballenthin** [comment]
rather than maintaining two version of the script, i think we should target the latest release of IDA. in the readme we can link to the git commit of prior versions that support old versions of IDA.

with that in mind, would you merge update this PR to overwrite the existing `idb2pat`?

**Comment by KulaGGin** [comment]
Ok

**Comment by KulaGGin** [comment]
Updated. I force pushed, so the history is clean and we have one commit instead of 2.

**Review by williballenthin — APPROVED** [review]
looks great, thanks!

**Pull request merged**
